// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFN4xdeZQzbWNDqR63dmhLKRN-K_I2m3Q',
    appId: '1:642493579594:web:cace475811308b55d0c1b3',
    messagingSenderId: '642493579594',
    projectId: 'eghtanem-app',
    authDomain: 'eghtanem-app.firebaseapp.com',
    storageBucket: 'eghtanem-app.appspot.com',
    measurementId: 'G-N8SGE2HSQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8l-E85rvBrN-gZGypqEypHlLstf6Yhc0',
    appId: '1:642493579594:android:9722d4d06bd0af2dd0c1b3',
    messagingSenderId: '642493579594',
    projectId: 'eghtanem-app',
    storageBucket: 'eghtanem-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLtiVpm7df_J9nYrTjXdWIw2gs8QgckQg',
    appId: '1:642493579594:ios:7d69e2f883777173d0c1b3',
    messagingSenderId: '642493579594',
    projectId: 'eghtanem-app',
    storageBucket: 'eghtanem-app.appspot.com',
    iosClientId: '642493579594-k67a5crrmpqi09tojojtmu902n8dief5.apps.googleusercontent.com',
    iosBundleId: 'com.example.egtanemApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLtiVpm7df_J9nYrTjXdWIw2gs8QgckQg',
    appId: '1:642493579594:ios:7d69e2f883777173d0c1b3',
    messagingSenderId: '642493579594',
    projectId: 'eghtanem-app',
    storageBucket: 'eghtanem-app.appspot.com',
    iosClientId: '642493579594-k67a5crrmpqi09tojojtmu902n8dief5.apps.googleusercontent.com',
    iosBundleId: 'com.example.egtanemApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFN4xdeZQzbWNDqR63dmhLKRN-K_I2m3Q',
    appId: '1:642493579594:web:998e9cf91d6ced25d0c1b3',
    messagingSenderId: '642493579594',
    projectId: 'eghtanem-app',
    authDomain: 'eghtanem-app.firebaseapp.com',
    storageBucket: 'eghtanem-app.appspot.com',
    measurementId: 'G-C5RQ0S5F6X',
  );
}
